### ISSUE TITLE
MySQL only?

### ISSUE THREAD

**Issue by vaughany** [thedevsaddam/laravel-schema#1]
Hiya. Just installed your package into Laravel 5.3 w/ Postgres and received the following error:

```
$ ./artisan schema:show
[Illuminate\Database\QueryException]
SQLSTATE[42704]: Undefined object: 7 ERROR:  unrecognized configuration parameter "tables" (SQL: SHOW TABLES)
[PDOException]
SQLSTATE[42704]: Undefined object: 7 ERROR:  unrecognized configuration parameter "tables"
```

Is this because the package is MySQL only? I notice that at the bottom it says "Multiple database facility coming soon", but it doesn't say what database is currently supported.

Cheers!

**Comment by thedevsaddam** [comment]
@vaughany  Currently working with Mysql. Multiple database functionalities will be added soon.

**Comment by thedevsaddam** [comment]
@vaughany please use 1.1.0 for Postgres sql.
